spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Prabhu@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: inventory-service

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
