server:
  port: 8081

eureka:
  instance:
    hostname: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: Prabhu@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

#Kafka properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping:
                event: com.sirji.event.OrderPlacedEvent


#Activating resilience endpoints to connect with actuators
#management:
#  health:
#    circuitbreakers:
#      enabled: true

#Resilience4j properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

#Resilience4j Timeout properties
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s

#Resilience4j Retry properties
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s